FreeBSD_task:
  freebsd_instance:
    image_family: freebsd-12-0

  env:
    HOME: /root

  install-packages_script: ./scripts/packages.sh

  download-prerequisites_script: ./scripts/download.sh

  checkout-repos:script: ./scripts/checkout.sh

  print-info_script: |
    cmake --version
    git --version
    vagrant --version
    rsync --version
    dmesg -a

  run-vagrant_script: ./scripts/runVagrant.sh

  update-linux-dependencies_script: ./scripts/updateVagrant.sh

  build-product_script: ./scripts/build.sh
