FreeBSD_task:
  freebsd_instance:
    image_family: freebsd-12-1

  env:
    HOME: /root
    PATH: $PATH:/root/.dotnet
    DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1

  load linux module_script: |
    kldload linux64 linprocfs
    kldstat

  install packages_script: |
    pkg update
    pkg install -y bash emulators/linux_base-c7

  mount procfs_script: |
    mount -t linprocfs linprocfs /compat/linux/proc

  install dotnet_script: |
    curl -sSLO https://dot.net/v1/dotnet-install.sh
    sed -i '' 's/echo "freebsd"/echo "linux"/' dotnet-install.sh
    chmod +x dotnet-install.sh
    ./dotnet-install.sh --version 5.0.100-preview.8.20362.3

  emulate dotnet_script: |
    dotnet --info
    dotnet new console -n hwapp
    dotnet run -p hwapp
