Linux_task:
  container:
    image: ubuntu:latest

  install package_script: apt update && apt install -y gcc curl

  build hack (managed)_script: echo "/* coreclr-27955-workaround.c */ int sched_getcpu(void) { return 0; }" | gcc -xc -shared -o libcoreclr-27955-workaround.so -

  publish_script: curl -s -X POST --data-binary @libcoreclr-27955-workaround.so http://$CIRRUS_HTTP_CACHE_HOST/libcoreclr-27955-workaround.so

FreeBSD_task:
  freebsd_instance:
    image_family: freebsd-12-0

  depends_on: Linux

  env:
    HOME: /root
    PATH: $PATH:/root/.dotnet
    DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1

  load linux module_script: |
    kldload linux64 linprocfs
    kldstat

  install packages_script: |
    pkg install -y bash emulators/linux_base-c7

  mount procfs_script: |
    mount -t linprocfs linprocfs /compat/linux/proc

  install dotnet_script: |
    curl -sSLO https://dot.net/v1/dotnet-install.sh
    sed -i '' 's/echo "freebsd"/echo "linux"/' dotnet-install.sh
    chmod +x dotnet-install.sh
    ./dotnet-install.sh -Channel 3.1

  download workaround .so_script: curl -vO http://$CIRRUS_HTTP_CACHE_HOST/libcoreclr-27955-workaround.so

  emulate dotnet_script: |
    LD_PRELOAD=$(pwd)/libcoreclr-27955-workaround.so     dotnet --info
    LD_PRELOAD=$(pwd)/libcoreclr-27955-workaround.so     dotnet new console -n hwapp
    LD_PRELOAD=$(pwd)/libcoreclr-27955-workaround.so     dotnet run -p hwapp
