Linux_task:

  container:
    image: mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-cross-freebsd-12-20200407092345-a84b0d2

  env:
    ROOTFS_DIR: /crossrootfs/x64

  clone runtime_script: git clone https://github.com/dotnet/runtime --branch master --single-branch --depth 1

  build coreclr_script: runtime/src/coreclr/build-runtime.sh release x64 -cross -os FreeBSD -ci -clang9
